<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// SPA catch-all — unauthenticated redirects land here
Route::get('/login', function () {
    return view('welcome');
})->name('login');

// API Documentation (generated by Scribe — run `php artisan scribe:generate`)
Route::get('/docs/api', function () {
    return view('scribe.index');
})->name('docs.api');
