<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// API Documentation (generated by Scribe — run `php artisan scribe:generate`)
Route::get('/docs/api', function () {
    return view('scribe.index');
})->name('docs.api');
