<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// SPA catch-all — unauthenticated redirects land here
Route::get('/login', function () {
    return view('welcome');
})->name('login');

// API Documentation (generated by Scribe — run `php artisan scribe:generate`)
Route::get('/docs/api', function () {
    return view('scribe.index');
})->name('docs.api');

// SPA catch-all — must be last. Serves the React app for all deep-linked routes
// (e.g. /events, /admin/users). Installer/update routes take priority because
// they are registered first by their ServiceProviders.
Route::get('/{any}', function () {
    return view('welcome');
})->where('any', '.*')->name('spa.catchall');
